### PR TITLE
Enhance the FEV1 data comparison vignette

### PR DESCRIPTION
**Pull request by wlandau**
This pull request proposes improvements the FEV1 data comparison vignette:

1. Noticeably improve agreement between the Bayesian and frequentist models by:
    * Increasing the number of MCMC chains and iterations, and
    * Setting a diffuse prior on the intercept.
2. Expand the prose, especially the conclusion at the end.
3. Rename the vignette to `fev1.Rmd` to make room for a separate comparison vignette on the BCVA data.
4. Tidy up code style.

@chstock, would you please review?

### CODE REVIEW

**Comment by chstock** [comment]
I added a few (minor) comments https://github.com/openpharma/brms.mmrm/commit/67cd8f32b485774ad7f54d19bbccd20f41fbef51#comments.

**Comment by wlandau** [comment]
Thanks for the review, @chstock! I believe I addressed your comments in recent commits.

**Comment by chstock** [comment]
> Thanks for the review, @chstock! I believe I addressed your comments in recent commits.

Yes, definitely looks all good to me! Thanks!

**Comment by wlandau** [comment]
> Yes, definitely looks all good to me! Thanks!

Awesome, thanks again for your review!

**Pull request merged**
